export interface Lane {
  name: string;
  pain: string;
  offers: string[];
  signals: string[];
  subreddits: string[];
  searches: string[];
  skip: string;
  color: {
    border: string;
    bg: string;
    chip: string;
    accent: string;
  };
}

export const LANES: Lane[] = [
  {
    name: "Career Story",
    pain: "They have experience but cannot explain it cleanly.",
    offers: [
      "Career Story Map / Working Life Starter Map",
      "Professional Story Translation",
      "Founder Story Starter",
      "Body of Knowledge / Intellectual Asset Map",
    ],
    signals: [
      "I have done a lot of different things",
      "My resume is all over the place",
      "I do not know how to explain my background",
      "Changing careers",
      "Nonlinear career",
      "Career pivot",
      "LinkedIn profile",
      "How do I position myself",
      "Returning to work",
      "Second career",
      "Too old to start over",
    ],
    subreddits: [
      "r/careerguidance",
      "r/careerchange",
      "r/findapath",
      "r/jobs",
      "r/resumes",
      "r/linkedin",
      "r/GenX",
      "r/AskOldPeopleAdvice",
      "r/overemployed",
      "r/freelance",
    ],
    searches: [
      'r/careerguidance "career change" "experience"',
      'r/careerchange "LinkedIn" "career"',
      'r/findapath "done a lot of different things"',
      'r/resumes "career change" "resume"',
      'r/linkedin "changing careers"',
      'r/jobs "nonlinear career"',
      'r/careerguidance "too old" "career"',
      'r/GenX "career change"',
    ],
    skip: "Skip young people who only need basic job advice unless the issue is clearly story and positioning.",
    color: {
      border: "border-indigo-500/50",
      bg: "bg-indigo-500/5 dark:bg-indigo-500/10",
      chip: "bg-indigo-500/15 text-indigo-700 dark:text-indigo-300",
      accent: "text-indigo-600 dark:text-indigo-400",
    },
  },
  {
    name: "AI Confidence",
    pain: "They know AI could help but do not know where to begin.",
    offers: ["AI Confidence Starter", "Custom AI Starter Map", "AI Workflow Focus"],
    signals: [
      "I'm overwhelmed by AI",
      "Where do I start with ChatGPT",
      "I'm not tech savvy",
      "I run a small business and want to use AI",
      "How can AI help my business",
      "I tried ChatGPT and got generic answers",
      "What should I use AI for",
      "One practical AI use",
      "AI for my daily workflow",
    ],
    subreddits: [
      "r/AiForSmallBusiness",
      "r/ChatGPT",
      "r/ChatGPTPromptGenius",
      "r/smallbusiness",
      "r/Entrepreneur",
      "r/freelance",
      "r/solopreneur",
      "r/EtsySellers",
      "r/Teachers",
      "r/therapists",
    ],
    searches: [
      'r/AiForSmallBusiness "zero tech skills"',
      'r/smallbusiness "how to use AI"',
      'r/Entrepreneur "ChatGPT" "generic"',
      'r/ChatGPT "small business" "overwhelmed"',
      'r/ChatGPTPromptGenius "grow my business"',
      'r/freelance "AI tools" "where do I start"',
      'r/EtsySellers "AI" "product descriptions"',
    ],
    skip: "Skip AI hobbyists and tool collectors who want a list. The real lead says: I have a real task and I do not know how to use AI for it.",
    color: {
      border: "border-emerald-500/50",
      bg: "bg-emerald-500/5 dark:bg-emerald-500/10",
      chip: "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300",
      accent: "text-emerald-600 dark:text-emerald-400",
    },
  },
  {
    name: "Knowledge to Video",
    pain: "They know something but cannot turn it into content.",
    offers: [
      "Knowledge-to-Video Starter",
      "Knowledge Extraction System",
      "Knowledge-to-Video Production Workflow",
      "Knowledge-to-Video Starter Packet",
      "Body of Knowledge / Intellectual Asset Map",
    ],
    signals: [
      "I want to start YouTube but",
      "I have expertise but do not know what to post",
      "How do I turn my knowledge into content",
      "I hate making videos",
      "I do not know how to script",
      "I have notes everywhere",
      "How do I make educational content",
      "I want to create a course",
      "I do not know what my first video should be",
    ],
    subreddits: [
      "r/NewTubers",
      "r/youtubers",
      "r/SmallYoutubers",
      "r/podcasting",
      "r/content_marketing",
      "r/CreatorServices",
      "r/onlinecourses",
      "r/Entrepreneur",
      "r/smallbusiness",
      "r/Teachers",
      "r/instructionaldesign",
    ],
    searches: [
      'r/NewTubers "I want to start" "YouTube"',
      'r/NewTubers "not an expert"',
      'r/NewTubers "script"',
      'r/podcasting "turn into episodes"',
      'r/onlinecourses "course idea"',
      'r/Teachers "YouTube channel"',
      'r/content_marketing "thought leadership"',
      'r/smallbusiness "make videos"',
    ],
    skip: "Skip monetization hackers, viral chasers and gear questioners. Your buyer has knowledge organization pain, not gear pain.",
    color: {
      border: "border-rose-500/50",
      bg: "bg-rose-500/5 dark:bg-rose-500/10",
      chip: "bg-rose-500/15 text-rose-700 dark:text-rose-300",
      accent: "text-rose-600 dark:text-rose-400",
    },
  },
  {
    name: "Founder Story",
    pain: "They built something but cannot explain it clearly.",
    offers: [
      "Founder Story Starter",
      "Professional Story Translation",
      "Body of Knowledge / Intellectual Asset Map",
      "Knowledge Extraction System",
      "AI Workflow Focus",
    ],
    signals: [
      "How do I explain my startup",
      "Positioning",
      "Messaging",
      "Landing page feedback",
      "Storytelling as a founder",
      "I built this for myself",
      "Nobody understands what I do",
      "How do I describe my product",
      "My copy is not converting",
      "Need help with my pitch",
      "Too many features",
      "What problem am I solving",
    ],
    subreddits: [
      "r/startups",
      "r/Entrepreneur",
      "r/SaaS",
      "r/ProductMarketing",
      "r/buildinpublic",
      "r/indiehackers",
      "r/SideProject",
      "r/smallbusiness",
      "r/marketing",
      "r/copywriting",
    ],
    searches: [
      'r/startups "positioning"',
      'r/SaaS "landing page feedback"',
      'r/ProductMarketing "founder positioning"',
      'r/buildinpublic "built this for myself"',
      'r/Entrepreneur "how do I explain my business"',
      'r/SideProject "feedback on my idea"',
      'r/SaaS "too many features"',
      'r/startups "pitch" "story"',
    ],
    skip: "Skip founders fishing for free labor or validation. Good leads have a live product, a messy message and urgency to pay for clarity.",
    color: {
      border: "border-amber-500/50",
      bg: "bg-amber-500/5 dark:bg-amber-500/10",
      chip: "bg-amber-500/15 text-amber-700 dark:text-amber-300",
      accent: "text-amber-600 dark:text-amber-400",
    },
  },
  {
    name: "Time to Money",
    pain: "They cannot convert time, options or activity into a clear plan.",
    offers: [
      "Time-to-Money Calculator",
      "Execution Friction Mini-Audit Template / Self-Map",
      "Execution Friction Audit",
      "Career Story Map",
      "AI Confidence Starter",
    ],
    signals: [
      "I need to make money fast",
      "I have 2 hours a day",
      "How do I make $500",
      "I keep starting and stopping",
      "Too many ideas",
      "What should I focus on",
      "I need a realistic plan",
      "How do I price this",
      "How many clients do I need",
      "Side hustle but no time",
      "Analysis paralysis",
    ],
    subreddits: [
      "r/sidehustle",
      "r/Entrepreneur",
      "r/smallbusiness",
      "r/freelance",
      "r/povertyfinance",
      "r/beermoney",
      "r/overemployed",
      "r/GenX",
      "r/findapath",
    ],
    searches: [
      'r/sidehustle "$500" "month"',
      'r/Entrepreneur "too many ideas"',
      'r/freelance "how do I price"',
      'r/smallbusiness "what should I focus on"',
      'r/findapath "need to make money"',
      'r/sidehustle "2 hours a day"',
      'r/GenX "side hustle"',
    ],
    skip: "Skip desperate need-money-tomorrow posts unless they have skill, context and a solvable structure problem.",
    color: {
      border: "border-cyan-500/50",
      bg: "bg-cyan-500/5 dark:bg-cyan-500/10",
      chip: "bg-cyan-500/15 text-cyan-700 dark:text-cyan-300",
      accent: "text-cyan-600 dark:text-cyan-400",
    },
  },
];

export const LANE_NAMES = LANES.map((l) => l.name);

export function getLane(name: string | null): Lane | undefined {
  return LANES.find((l) => l.name === name);
}
